// Package sshcfg renders the ssh_config that lets `ssh <vm>.cracklet` reach a microVM
// through the Lima VM as a jump host.
package sshcfg

import (
	"bytes"
	"fmt"
	"text/template"
)

// Options parameterise the rendered configuration.
type Options struct {
	// Instance is the Lima instance name; hosts are addressed as <vm>.<Instance>.
	Instance string
	// KeyPath is the private key injected into every microVM.
	KeyPath string
	// LimaSSHConfig is Lima's generated ssh_config for the instance.
	LimaSSHConfig string
}

var tmpl = template.Must(template.New("ssh_config").Parse(`# Generated by cracklet. Reach microVMs with: ssh <name>.{{.Instance}}
# Add "Include {{.Path}}" to ~/.ssh/config to use the alias with plain ssh.
Host *.{{.Instance}}
  User root
  IdentityFile {{.KeyPath}}
  ProxyCommand ssh -F {{.LimaSSHConfig}} -W %h:%p lima-{{.Instance}}
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
  LogLevel ERROR
`))

// Render produces the ssh_config text.
func Render(o Options) (string, error) {
	if o.Instance == "" || o.KeyPath == "" || o.LimaSSHConfig == "" {
		return "", fmt.Errorf("instance, key path and lima ssh config are required")
	}
	var buf bytes.Buffer
	data := struct {
		Options
		Path string
	}{Options: o, Path: "~/.cracklet/ssh_config"}
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("render ssh config: %w", err)
	}
	return buf.String(), nil
}

// HostAlias returns the ssh host name for a microVM.
func HostAlias(name, instance string) string {
	return name + "." + instance
}
